"""
This Program is intended to count the number of each nucleotide in a given DNA sequence string.
The four nucleotides are: 'A', 'C', 'G', and 'T'
"""

def nucleotide_count (DNA_string: str) -> str:
    adenine_count = 0
    cytosine_count = 0
    guanine_count = 0
    thymine_count = 0
    for nucleotide in DNA_string:
        if nucleotide.upper() == 'A':
            adenine_count += 1
        elif nucleotide.upper() == 'C':
            cytosine_count += 1
        elif nucleotide.upper() == 'G':
            guanine_count += 1
        elif nucleotide.upper() == 'T':
            thymine_count += 1
    return (adenine_count, cytosine_count, guanine_count, thymine_count)

Rosalind_DNA_string = 'GGGACATCAACCGTATAGGAGATGTCTGCTTTACACGTCGGCTACTGTAAACTAGATATGGCGTAATAAGGTGGAATCTGTTTCAGTTTGACCAGTCATGCGTGACGGGTATGGAAGTTAGATGGCCTACGGAAATCATTAACCACCCAGGTACATTTCTCTGCAGTTTAGCCGTCAAAGGACGGCGTGATCAGATCCTATGACGAGGATGTTGACTAAGTTATTTCGCGGACAGCAGGGTGCGTGCCCACCACCCAGGCGTGCGTATTCCCGTGAGATAGTACTACTTTCTTATGTCGGTGACACCTGGAGGCAGGCGTATACTTCAAGTCTAGGTGCTTGACTTAAGGACCACGTTCGATAGCGTTGATATGTCTCAAACATTCGCGATTTGGCGAGACCAAATCCGCGAGTTAAGCGCTTCGAAACACCGTAGCGCTGCTTAGGGAATTCGCCGAACTGACTAATCACTGAAAAGGTCGCAAGAGGTCCGCCAGCCGGTATCATATAGGGGCGGTAACACCCCCCCTTTGCAGAGCCTCTTCCCCCGGATTAATGTAGTGCACTGCCCGGAATCTCAAGCCAGGTATGTAGCCCGCGTGATATTTCGGTAGGACTGGGCGCGGGTCGGACAAGACAGCTTTAGGGCTGCAATGGCCTCATGTACGACCTGCCGGGGTGCGCCCTTACTGCGGCCCTCGCTAACGTCCTGAGGTAGTTCTGGAATCTGACCATACATACTAAAAAGGTTAGGCGAAGGCCCGTCAAGCACAAAGTTTCATCGTACTCTAACAAACAGAGGTTTCGTTTCCTCAATAAACGAAAGCGTCGCTCGTCCAGGCTGTAGTATATACTATCAATCTAATTATATTGCGCGGAGGTTTCAACCTGGCGTTACCCTTTAACTTCCATCCTCCGAACCCATC'
print(nucleotide_count(Rosalind_DNA_string))