"""
This Program is intended to transform a DNA string into an RNA string from a given DNA sequence string.
The four nucleotides in DNA are: 'A', 'C', 'G', and 'T'
The four nucleotides in RNA are: 'A', 'C', 'G', and 'U'
The goal is to turn 'T' into 'U'
"""

def DNA_to_RNA(DNA_string: str) -> str:
    RNA_string = ''
    
    for nucleotide in DNA_string:
        if nucleotide. upper() == 'T':
            RNA_string += 'U'
        else:
            RNA_string += nucleotide
    return RNA_string

Rosalind_DNA_string = 'GCTGCGCGTATGTCATTAAAATTCATACGAATCGCAGAGGTACGCGCAGATCCTGTTTTGGGGACGCTCATTGACGCGTCCTAACCTGAAATCGTTTGGTGGCGGCAACTGGTTCGCGCGCACCTCATAGGCGCCATAGAGGATAACAGGGGCAATACGTTGTTCCGGTGTTGGGTGTTTCGGACCATCCGGTTTGTTTGGGAAGCAGGGAGTTAAGTTCAACCCGCGGACTCCTGATGCGGCGCTAGCATGGCGGGCATGGTTCCGCAATGAACTAGTGAATGTACGACATCTTGCCATGGCTGCACTCATGACATTAACACTAGGTCAGATTCTGCCTGCCAGAAAGTGAACCAGCTACTGTGGCTCCTGGGTAACTGTTGCGATGAAATTTGCTTATTCGGTCGCAGATACAGGTCACTGTATACTGATCGTACTGGTCCCATAGCCACACCCTCTCATGACGAAATCGGGGGTCCCGACATCCGGCGCCCGCAACTGTGTTTAACTGGACTATGGTCTCGTCAGCAGTAGTGTATTTGCCTTTGCTGATTTTTCTCGACCGCTTCCCGTCGCGAGGGGTGGAGTCACACGTGAGCTAGAGACGTAAGGCGCGGAATGCAATGGGTCTGTGAAGTCGTTGGCATGACCCGGAGCTTAATGAACGACTGCGGAGATGGCACGCGAAGTTGAATCCTTCATGTAACTTTATTCTATCATTCTGCTAATTGCATGCTTAATTAATCGGCGGTCCATGGACGTAGACCCCTACTGCGGCCGTACTTAGTGACGGTTCAATTCAAAGTGCCATAGTCTACTACCATTGTTCATCGAGAAAGCTTGTCGAATTTCGCTACATTAAACAACCCACCTCGATGCAAGAACCAATTGAAAACCTAGAATCTCAGTTGCAGGAGATAGGCTCGTATAATCTAGCGTTGGCGTACGCAAGTCGAGTTCGTCGGGTCTATGGTTATCGTGTCAGGCTAGG'
print(DNA_to_RNA(Rosalind_DNA_string))